service: sonotheque

image: sachaandre/sonotheque

servers:
  web:
    - 83.228.218.180

proxy:
  ssl: true
  host: jjbirge-sonotheque.sachaandre.com

registry:
  username: sachaandre
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_LOG_LEVEL: info

volumes:
  - "sonotheque_storage:/rails/storage"

builder:
  arch: amd64

ssh:
  user: debian